# Generated by Django 5.1.6 on 2025-03-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_person_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='partner',
        ),
        migrations.AddField(
            model_name='person',
            name='partners',
            field=models.ManyToManyField(blank=True, related_name='partners', to='family.person'),
        ),
    ]
