# Generated by Django 5.1.6 on 2025-03-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0003_remove_person_partner_person_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='root',
            field=models.BooleanField(default=False, verbose_name='root'),
        ),
    ]
